### ISSUE TITLE
The thumbnail generator fails to copy to /tmp/

### ISSUE THREAD

**Issue by Orsucciu** [biblibre/omeka-s-module-CreateMissingThumbnails#1]
Hello,

I tried to regenerate my missing thumbnails with your module, but i encountered a problem.

In my error logs, i would get

 Thumbnails creation failed for media 2086: Failed to copy /var/www/Limunata_litteraria/files/original/93128024e4e53cfa9b7d4d0d12c69290410ba4c4 to /tmp/omekampN31r

I checked the permissions, and they seem correct

#ls -laZ /
drwxrwxrwx  53 root root ?  4096 May 17 09:15 tmp

As a matter of fact, the user www-data even has temp files written inside this folder, so i see nothing wrong.

I try to create a new temp folder, (/var/www/temp/), give it 777 and use it instead, but i got the same error

Thumbnails creation failed for media 2082: Failed to copy /var/www/Limunata_litteraria/files/original/2039336f682806bd64c3485c14e10a07fa07ec6c to /var/www/temp/omeka1EMTrp

And what’s even stranger, is that the /var/www/temp/ folder is filled with the temporary files, except that their permission is 500, and that they all weight only 1.
Those temporary files aren't owned by www-data, but by administrator (the user).

Do you have any idea of what would cause this ? 

Thanks

**Comment by jajm** [comment]
Have you checked that `/var/www/Limunata_litteraria/files/original/2039336f682806bd64c3485c14e10a07fa07ec6c` exist ? Maybe the problem is not with the destination, but with the source
Files in `original` directory normally have an extension in their name (.png, .pdf, ...) and that's not the case here.
Are there any other enabled modules ?

**Comment by Orsucciu** [comment]
hi, yes it does exists, but with the extension .pdf; calling directly 
`<server>/files/original/2039336f682806bd64c3485c14e10a07fa07ec6c` gives nothing, but manually adding .pdf after works

**Comment by jajm** [comment]
Can you execute the following SQL query and paste the results here:

```sql
select * from media where storage_id = '2039336f682806bd64c3485c14e10a07fa07ec6c'
```

**Comment by Orsucciu** [comment]
Wow somehow my extensions are broken....

![image](https://user-images.githubusercontent.com/12692291/168851098-af6116b4-473e-430d-8c1a-f65da20c6e78.png)

I'll try to fix it and come back. Thanks!

**Comment by jajm** [comment]
Closed as it appears it's not a bug in CreateMissingThumbnails. But feel free to comment if you find something
